<?php

declare(strict_types=1);

namespace App\Providers;

use App\Models\PasskeyCredential;
use App\Models\User;
use App\Policies\PasskeyCredentialPolicy;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        // autogenerated
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Gate::policy(PasskeyCredential::class, PasskeyCredentialPolicy::class);

        // Hinweis: LogRoleChangeListener wird von Laravels Event-Auto-Discovery
        // erfasst (handle*-Methoden mit Event-Typ-Hint in app/Listeners/). Eine
        // zusätzliche explizite Event::listen()-Registrierung würde den Listener
        // doppelt aufrufen — jede Rollenänderung landet sonst zweimal im Activity-Log.

        // Passkey authentication options (guests): IP-based, 20 requests per minute.
        // Limits e-mail enumeration via the allowCredentials field without impacting
        // legitimate UX (a real user needs at most one options call per login attempt).
        RateLimiter::for(
            'passkey-authenticate-options',
            static fn (Request $request): Limit => Limit::perMinute(20)->by($request->ip()),
        );

        // Passkey authentication (guests): IP-based, 5 attempts per minute.
        // Protects against credential enumeration and brute-force via the public endpoint.
        RateLimiter::for(
            'passkey-authenticate',
            static fn (Request $request): Limit => Limit::perMinute(5)->by($request->ip()),
        );

        // Passkey registration (authenticated users): user-based, 5 attempts per minute.
        // Falls back to IP when no authenticated user is available.
        RateLimiter::for('passkey-register', static function (Request $request): Limit {
            $user = $request->user();

            return $user instanceof User
                ? Limit::perMinute(5)->by((string) $user->id)
                : Limit::perMinute(5)->by($request->ip());
        });
    }
}
