<?php

declare(strict_types=1);

namespace App\Providers;

use App\Models\PasskeyCredential;
use App\Models\User;
use App\Policies\PasskeyCredentialPolicy;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        // autogenerated
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Stabile Aliase für polymorphe Beziehungen — primär für den Activity-Log,
        // damit `subject_type` / `causer_type` keine FQCN enthalten (refactor-sicher,
        // entkoppelt DB-Daten von Klassen-Namen, übersetzbar im UI).
        //
        // `enforceMorphMap` (statt `morphMap`) wirft eine `ClassMorphViolationException`,
        // sobald ein Model mit polymorpher Beziehung NICHT in der Map steht. Das ist
        // beabsichtigt: bei einem neuen Loggable-Model fliegt der Fehler sofort beim
        // ersten Schreibversuch, statt jahrelang stille FQCN in die DB zu schreiben.
        // Der Architektur-Test `tests/Feature/ActivityLog/MorphMapTest.php` schützt
        // zusätzlich gegen vergessene Einträge.
        Relation::enforceMorphMap([
            'user' => User::class,
            'passkey' => PasskeyCredential::class,
        ]);

        Gate::policy(PasskeyCredential::class, PasskeyCredentialPolicy::class);

        // Passkey authentication options (guests): IP-based, 20 requests per minute.
        // Limits e-mail enumeration via the allowCredentials field without impacting
        // legitimate UX (a real user needs at most one options call per login attempt).
        RateLimiter::for(
            'passkey-authenticate-options',
            static fn (Request $request): Limit => Limit::perMinute(20)->by($request->ip()),
        );

        // Passkey authentication (guests): IP-based, 5 attempts per minute.
        // Protects against credential enumeration and brute-force via the public endpoint.
        RateLimiter::for(
            'passkey-authenticate',
            static fn (Request $request): Limit => Limit::perMinute(5)->by($request->ip()),
        );

        // Passkey registration (authenticated users): user-based, 5 attempts per minute.
        // Falls back to IP when no authenticated user is available.
        RateLimiter::for('passkey-register', static function (Request $request): Limit {
            $user = $request->user();

            return $user instanceof User
                ? Limit::perMinute(5)->by((string) $user->id)
                : Limit::perMinute(5)->by($request->ip());
        });
    }
}
